[package]
name = "bob"
version = "0.1.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
canonical = "0.6"
canonical_derive = "0.6"
dusk-abi = "0.9.0-rc"
rusk-abi = {path = "../../../../rusk-abi"}

[workspace]
