// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rusk.proto

package phoenix

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Provisioner struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provisioner) Reset()         { *m = Provisioner{} }
func (m *Provisioner) String() string { return proto.CompactTextString(m) }
func (*Provisioner) ProtoMessage()    {}
func (*Provisioner) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{0}
}

func (m *Provisioner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provisioner.Unmarshal(m, b)
}
func (m *Provisioner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provisioner.Marshal(b, m, deterministic)
}
func (m *Provisioner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provisioner.Merge(m, src)
}
func (m *Provisioner) XXX_Size() int {
	return xxx_messageInfo_Provisioner.Size(m)
}
func (m *Provisioner) XXX_DiscardUnknown() {
	xxx_messageInfo_Provisioner.DiscardUnknown(m)
}

var xxx_messageInfo_Provisioner proto.InternalMessageInfo

func (m *Provisioner) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type EchoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{1}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

type EchoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{2}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

type ValidateStateTransitionRequest struct {
	// List of transactions to be validated
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ValidateStateTransitionRequest) Reset()         { *m = ValidateStateTransitionRequest{} }
func (m *ValidateStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionRequest) ProtoMessage()    {}
func (*ValidateStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{3}
}

func (m *ValidateStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionRequest.Unmarshal(m, b)
}
func (m *ValidateStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionRequest.Merge(m, src)
}
func (m *ValidateStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionRequest.Size(m)
}
func (m *ValidateStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionRequest proto.InternalMessageInfo

func (m *ValidateStateTransitionRequest) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ValidateStateTransitionResponse struct {
	// Status of the state transition
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateStateTransitionResponse) Reset()         { *m = ValidateStateTransitionResponse{} }
func (m *ValidateStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionResponse) ProtoMessage()    {}
func (*ValidateStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{4}
}

func (m *ValidateStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionResponse.Unmarshal(m, b)
}
func (m *ValidateStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionResponse.Merge(m, src)
}
func (m *ValidateStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionResponse.Size(m)
}
func (m *ValidateStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionResponse proto.InternalMessageInfo

func (m *ValidateStateTransitionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DistributeRequest struct {
	TotalReward          uint64         `protobuf:"fixed64,1,opt,name=total_reward,json=totalReward,proto3" json:"total_reward,omitempty"`
	Addresses            []*Provisioner `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Pk                   *PublicKey     `protobuf:"bytes,3,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DistributeRequest) Reset()         { *m = DistributeRequest{} }
func (m *DistributeRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeRequest) ProtoMessage()    {}
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{5}
}

func (m *DistributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeRequest.Unmarshal(m, b)
}
func (m *DistributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeRequest.Marshal(b, m, deterministic)
}
func (m *DistributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeRequest.Merge(m, src)
}
func (m *DistributeRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeRequest.Size(m)
}
func (m *DistributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeRequest proto.InternalMessageInfo

func (m *DistributeRequest) GetTotalReward() uint64 {
	if m != nil {
		return m.TotalReward
	}
	return 0
}

func (m *DistributeRequest) GetAddresses() []*Provisioner {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *DistributeRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type DistributeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeResponse) Reset()         { *m = DistributeResponse{} }
func (m *DistributeResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeResponse) ProtoMessage()    {}
func (*DistributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{6}
}

func (m *DistributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeResponse.Unmarshal(m, b)
}
func (m *DistributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeResponse.Marshal(b, m, deterministic)
}
func (m *DistributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeResponse.Merge(m, src)
}
func (m *DistributeResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeResponse.Size(m)
}
func (m *DistributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeResponse proto.InternalMessageInfo

func (m *DistributeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type WithdrawRequest struct {
	Signature            []byte     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Address              []byte     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Value                uint64     `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Pk                   *PublicKey `protobuf:"bytes,4,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{7}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *WithdrawRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *WithdrawRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *WithdrawRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type WithdrawResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{8}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Provisioner)(nil), "phoenix.Provisioner")
	proto.RegisterType((*EchoRequest)(nil), "phoenix.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "phoenix.EchoResponse")
	proto.RegisterType((*ValidateStateTransitionRequest)(nil), "phoenix.ValidateStateTransitionRequest")
	proto.RegisterType((*ValidateStateTransitionResponse)(nil), "phoenix.ValidateStateTransitionResponse")
	proto.RegisterType((*DistributeRequest)(nil), "phoenix.DistributeRequest")
	proto.RegisterType((*DistributeResponse)(nil), "phoenix.DistributeResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "phoenix.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "phoenix.WithdrawResponse")
}

func init() {
	proto.RegisterFile("rusk.proto", fileDescriptor_211ec4e18343b18f)
}

var fileDescriptor_211ec4e18343b18f = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xb9, 0xef, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0x5a, 0xfa, 0x6b, 0x5f, 0xca, 0x51, 0xab, 0x88, 0x10, 0x10, 0x14, 0x0f, 0x34,
	0x03, 0xca, 0x10, 0xc4, 0xc4, 0x84, 0x04, 0x02, 0x89, 0x05, 0x99, 0x0a, 0x46, 0xe4, 0x26, 0x16,
	0xb5, 0x12, 0xc5, 0xc1, 0x47, 0x8f, 0x99, 0x9d, 0xff, 0x87, 0xff, 0x0e, 0xe5, 0x0e, 0xa5, 0xc7,
	0x96, 0x77, 0x7f, 0xfc, 0xbe, 0x2f, 0x00, 0xd2, 0xa8, 0x24, 0xc8, 0xa5, 0xd0, 0x02, 0xdd, 0xe4,
	0x1b, 0xc1, 0x32, 0xbe, 0xf7, 0x66, 0x5a, 0xd2, 0x4c, 0xd1, 0x48, 0x73, 0x91, 0x55, 0x31, 0x0f,
	0x12, 0x76, 0x50, 0xd5, 0x37, 0x5e, 0x82, 0xf3, 0x59, 0x8a, 0x2d, 0x57, 0x5c, 0x64, 0x4c, 0x22,
	0x17, 0x6e, 0x68, 0x1c, 0x4b, 0xa6, 0x94, 0x6b, 0x2d, 0x2c, 0x7f, 0x4a, 0x1a, 0x13, 0xdf, 0x01,
	0xe7, 0x7d, 0xb4, 0x11, 0x84, 0xfd, 0x34, 0x4c, 0x69, 0x7c, 0x17, 0xa6, 0x95, 0xa9, 0x72, 0x91,
	0x29, 0x86, 0x3f, 0xc2, 0xd3, 0xaf, 0x34, 0xe5, 0x31, 0xd5, 0xec, 0x8b, 0xa6, 0x9a, 0xad, 0x8a,
	0xa9, 0xbc, 0x18, 0x5a, 0x57, 0xa0, 0x17, 0x30, 0xd0, 0xfb, 0xa2, 0xed, 0xc0, 0x77, 0xc2, 0x79,
	0x50, 0xf3, 0x05, 0xab, 0x0e, 0x8f, 0x14, 0x09, 0xf8, 0x0d, 0x3c, 0x3b, 0xdb, 0xa9, 0x1a, 0x56,
	0x50, 0x2a, 0x13, 0x45, 0x0d, 0xe5, 0x98, 0x34, 0x26, 0xfe, 0x6d, 0xc1, 0xec, 0x1d, 0x57, 0x5a,
	0xf2, 0xb5, 0xd1, 0xac, 0x19, 0xfd, 0x1c, 0xa6, 0x5a, 0x68, 0x9a, 0x7e, 0x97, 0x6c, 0x47, 0x65,
	0x5c, 0x16, 0x8d, 0x88, 0x53, 0xfa, 0x48, 0xe9, 0x42, 0x21, 0x4c, 0xea, 0x97, 0x32, 0xe5, 0xda,
	0x47, 0x8c, 0xbd, 0x0d, 0x91, 0x2e, 0x0d, 0x61, 0xb0, 0xf3, 0xc4, 0x1d, 0x2c, 0x2c, 0xdf, 0x09,
	0x51, 0x97, 0x6c, 0xd6, 0x29, 0x8f, 0x3e, 0xb1, 0x03, 0xb1, 0xf3, 0x04, 0x07, 0x80, 0xfa, 0x3c,
	0x57, 0x1f, 0xf0, 0xcb, 0x82, 0x7b, 0xdf, 0xb8, 0xde, 0xc4, 0x92, 0xee, 0x1a, 0xfc, 0x27, 0x30,
	0x51, 0xfc, 0x47, 0x46, 0xb5, 0x91, 0xac, 0x96, 0xa5, 0x73, 0xf4, 0x25, 0xb3, 0xff, 0x91, 0x0c,
	0xcd, 0xe1, 0xf6, 0x96, 0xa6, 0x86, 0x95, 0x88, 0x23, 0x52, 0x19, 0x35, 0xf5, 0xf0, 0x22, 0xf5,
	0x4b, 0xb8, 0xdf, 0x41, 0x5c, 0x63, 0x0e, 0xff, 0xd8, 0x30, 0x24, 0x46, 0x25, 0xe8, 0x35, 0x0c,
	0x8b, 0xa3, 0x40, 0xdd, 0xe6, 0x7a, 0x27, 0xe3, 0x3d, 0x38, 0xf2, 0xd6, 0x97, 0x73, 0x0b, 0x65,
	0xf0, 0xf0, 0x8c, 0xe2, 0x68, 0xd9, 0xd6, 0x5c, 0xbe, 0x2e, 0xcf, 0xbf, 0x9e, 0xd8, 0xce, 0xfb,
	0x00, 0xd0, 0x69, 0x82, 0xbc, 0xb6, 0xf2, 0xbf, 0xc3, 0xf1, 0x1e, 0x9f, 0x8c, 0xb5, 0x8d, 0xde,
	0xc2, 0xb8, 0x59, 0x13, 0x72, 0xdb, 0xd4, 0x23, 0xf9, 0xbc, 0x47, 0x27, 0x22, 0x4d, 0x8b, 0xf5,
	0xa8, 0xfc, 0x0d, 0x5f, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x9c, 0x31, 0x8d, 0xbc, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RuskClient is the client API for Rusk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuskClient interface {
	// Simple echo request
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error)
	Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
}

type ruskClient struct {
	cc grpc.ClientConnInterface
}

func NewRuskClient(cc grpc.ClientConnInterface) RuskClient {
	return &ruskClient{cc}
}

func (c *ruskClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error) {
	out := new(ValidateStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/ValidateStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error) {
	out := new(DistributeResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Distribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuskServer is the server API for Rusk service.
type RuskServer interface {
	// Simple echo request
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(context.Context, *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error)
	Distribute(context.Context, *DistributeRequest) (*DistributeResponse, error)
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
}

// UnimplementedRuskServer can be embedded to have forward compatible implementations.
type UnimplementedRuskServer struct {
}

func (*UnimplementedRuskServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedRuskServer) ValidateStateTransition(ctx context.Context, req *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateTransition not implemented")
}
func (*UnimplementedRuskServer) Distribute(ctx context.Context, req *DistributeRequest) (*DistributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distribute not implemented")
}
func (*UnimplementedRuskServer) Withdraw(ctx context.Context, req *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}

func RegisterRuskServer(s *grpc.Server, srv RuskServer) {
	s.RegisterService(&_Rusk_serviceDesc, srv)
}

func _Rusk_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_ValidateStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).ValidateStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/ValidateStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).ValidateStateTransition(ctx, req.(*ValidateStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Distribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Distribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Distribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Distribute(ctx, req.(*DistributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rusk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phoenix.Rusk",
	HandlerType: (*RuskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Rusk_Echo_Handler,
		},
		{
			MethodName: "ValidateStateTransition",
			Handler:    _Rusk_ValidateStateTransition_Handler,
		},
		{
			MethodName: "Distribute",
			Handler:    _Rusk_Distribute_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Rusk_Withdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusk.proto",
}
