# The location for the base state to which apply this configuration
#
# The url can be either remote or local (eg: file:///path/state.zip)
# The content of the file shall be the same format generated 
# by `rusk recovery state --output <state.zip>` command
# If no base_state is specified a local one will be generated
base_state = "https://dusk-infra.ams3.digitaloceanspaces.com/keys/genesis.zip"

# Chain id configuration used to inject dusk consensus key
#
# Skipped if base_state is provided
# If chain_id is 0x01, the mainnet key will be used
# Otherwise, the testnet key will be used
chain_id = 0x00

# Balances to be included in the genesis contract
#
# Each balance is identified by an address, 
# a list of amounts in LUX (which is used to create each note), 
# and an optional seed (used during notes creation)
# 
# If no `seed` is configured, a random one is used.
[[phoenix_balance]]
address = 'dQgpVd2XwtXfVhDBdKX5rnXqyRkYsJgZ5wq826wdn6atfKnaNyptTogEko2u2ZWhW5sGADhR4YMKztqrFJphuMz'
seed = 0xcafe
notes = [
    1_000_000_000_000, 
    50_000_000, 
    245_123_000_423
]

[[phoenix_balance]]
address = '5i9RZjT87TLa1BtWXRRoFy3FoMzFHiXT3GWasHdUaxuo3YapUKYeXXiY1yuAeKng2hmxxaYsGNhKhjyrE9KYTSE7'
notes = [1_000_000_000_000]


# Accounts to be included in the genesis contract
#
# Each balance consists of an address (a BLS PublicKey in base58 format)
# and a balance.
[[moonlight_account]]
address = 'qe1FbZxf6YaCAeFNSvL1G82cBhG4Q4gBf4vKYo527Vws3b23jdbBuzKSFsdUHnZeBgsTnyNJLkApEpRyJw87sdzR9g9iESJrG5ZgpCs9jq88m6d4qMY5txGpaXskRQmkzE3'
balance = 1_000_000_000

# Stakes to be included in the stake contract
#
# Each stake is identified by the address (a BLS PublicKey in base58 format)
# and the staked amount (in LUX)
# 
# If no elegibility is configured, it defaults to 0. 
# Meaning that the stake is active from the genesis block
# 
# A preset `reward` amount can be configured (in LUX)
[[stake]]
address = 'tXxJU6caTEWicM7A4cNcPGa7dfGTXvnLuc1gWSSUGgyezSJNMfWEuAsiJrvWQjTzYeJCG8yL46LvtrBS5LqnXMNuamYpYiN3dEW6PDywURF6G6ZjFGNy9juHMFsSMdYx8EH'
amount = 1_000_000_000_000
elegibility = 1000
reward = 500_000

[[stake]]
address = 't7QRJHMJgtGuqfcUbaFNj6QmWyf1MdsRhZMZRdnWdFxEboE849EDLRyw9A6WPjNGvFcVMsq9P3TDfBDrnBRcH3xnmZiaFspQBRRkvv9jmzdvtgyQ1kVVjReHkNXNi9bGqz3'
amount = 1_000_000_000_000
