[wallet]

[rusk]
ipc_method = "tcp_ip"
rusk_addr = "https://nodes.dusk.network:8585"
prover_addr = "https://provers.dusk.network:8686"

[explorer]
tx_url = "https://explorer.dusk.network/transactions/transaction/?id="

[chain]
gql_url = "http://nodes.dusk.network:9500/graphql"
