[package]
name = "rusk-wallet"
version = "0.1.0"
description = "WASM modules for the Dusk wallet"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/rusk"

[[module]]
name = "rusk_wallet"
source = "../target/wasm32-unknown-unknown/release/rusk_wallet.wasm"
