// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package phoenix

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionInput struct {
	Pos                  *Idx       `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Sk                   *SecretKey `protobuf:"bytes,2,opt,name=sk,proto3" json:"sk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransactionInput) Reset()         { *m = TransactionInput{} }
func (m *TransactionInput) String() string { return proto.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()    {}
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *TransactionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInput.Unmarshal(m, b)
}
func (m *TransactionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInput.Marshal(b, m, deterministic)
}
func (m *TransactionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInput.Merge(m, src)
}
func (m *TransactionInput) XXX_Size() int {
	return xxx_messageInfo_TransactionInput.Size(m)
}
func (m *TransactionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInput proto.InternalMessageInfo

func (m *TransactionInput) GetPos() *Idx {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *TransactionInput) GetSk() *SecretKey {
	if m != nil {
		return m.Sk
	}
	return nil
}

type TransactionOutput struct {
	Note                 *Note      `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Pk                   *PublicKey `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Value                uint64     `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	BlindingFactor       *Scalar    `protobuf:"bytes,4,opt,name=blinding_factor,json=blindingFactor,proto3" json:"blinding_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransactionOutput) Reset()         { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string { return proto.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()    {}
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *TransactionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionOutput.Unmarshal(m, b)
}
func (m *TransactionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionOutput.Marshal(b, m, deterministic)
}
func (m *TransactionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionOutput.Merge(m, src)
}
func (m *TransactionOutput) XXX_Size() int {
	return xxx_messageInfo_TransactionOutput.Size(m)
}
func (m *TransactionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionOutput proto.InternalMessageInfo

func (m *TransactionOutput) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

func (m *TransactionOutput) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *TransactionOutput) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionOutput) GetBlindingFactor() *Scalar {
	if m != nil {
		return m.BlindingFactor
	}
	return nil
}

type Transaction struct {
	Nullifiers           []*Nullifier         `protobuf:"bytes,1,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	Outputs              []*TransactionOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetNullifiers() []*Nullifier {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *Transaction) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionInput)(nil), "phoenix.TransactionInput")
	proto.RegisterType((*TransactionOutput)(nil), "phoenix.TransactionOutput")
	proto.RegisterType((*Transaction)(nil), "phoenix.Transaction")
}

func init() {
	proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490)
}

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0x3f, 0xdf, 0x57, 0xe9, 0x06, 0x28, 0xb5, 0x18, 0xa2, 0x0c, 0xa8, 0x64, 0xea,
	0x94, 0xa1, 0x30, 0xf0, 0x04, 0x48, 0x15, 0x52, 0x41, 0x06, 0xb1, 0x22, 0x27, 0x71, 0xc0, 0x8a,
	0x65, 0x5b, 0xb6, 0x03, 0xed, 0x2b, 0xf1, 0x94, 0xc8, 0x4e, 0x93, 0x06, 0x75, 0xbb, 0xc9, 0x39,
	0xe7, 0xe7, 0xe3, 0x6b, 0x58, 0x58, 0x4d, 0x84, 0x21, 0x95, 0x65, 0x52, 0x14, 0x4a, 0x4b, 0x2b,
	0xd1, 0x4c, 0x7d, 0x4a, 0x2a, 0xd8, 0x2e, 0x4b, 0x1a, 0x46, 0x79, 0xdd, 0xff, 0xcd, 0xa0, 0xa5,
	0x7b, 0x33, 0xcc, 0x42, 0x5a, 0xda, 0xcf, 0xf9, 0x1b, 0x5c, 0xbe, 0x1e, 0x11, 0x1b, 0xa1, 0x3a,
	0x8b, 0xae, 0x21, 0x52, 0xd2, 0xa4, 0xc1, 0x32, 0x58, 0x25, 0xeb, 0xb3, 0xe2, 0xc0, 0x2b, 0x36,
	0xf5, 0x0e, 0x3b, 0x01, 0xe5, 0x10, 0x9a, 0x36, 0x0d, 0xbd, 0x8c, 0x46, 0xf9, 0x85, 0x56, 0x9a,
	0xda, 0x47, 0xba, 0xc7, 0xa1, 0x69, 0xf3, 0x9f, 0x00, 0x16, 0x13, 0xf0, 0x53, 0x67, 0x1d, 0xf9,
	0x06, 0x62, 0x77, 0xf6, 0x01, 0x7d, 0x3e, 0x66, 0xb7, 0xd2, 0x52, 0xec, 0x25, 0x07, 0x57, 0xa7,
	0xf0, 0xe7, 0xae, 0xe4, 0xac, 0xf2, 0x70, 0xd5, 0xa2, 0x2b, 0xf8, 0xf7, 0x45, 0x78, 0x47, 0xd3,
	0x68, 0x19, 0xac, 0x62, 0xdc, 0x7f, 0xa0, 0x7b, 0x98, 0x97, 0x9c, 0x89, 0x9a, 0x89, 0x8f, 0xf7,
	0x86, 0x54, 0x56, 0xea, 0x34, 0xf6, 0x98, 0xf9, 0xb1, 0x63, 0x45, 0x38, 0xd1, 0xf8, 0x62, 0xf0,
	0x3d, 0x78, 0x5b, 0xfe, 0x0d, 0xc9, 0xa4, 0x2b, 0x5a, 0x03, 0x88, 0x8e, 0x73, 0xd6, 0x30, 0xaa,
	0xdd, 0x1a, 0xa2, 0x3f, 0x55, 0xb6, 0x83, 0x84, 0x27, 0x2e, 0x74, 0x07, 0x33, 0xe9, 0xef, 0x68,
	0xd2, 0xd0, 0x07, 0xb2, 0x31, 0x70, 0xb2, 0x06, 0x3c, 0x58, 0xcb, 0xff, 0xfe, 0x11, 0x6e, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x32, 0x71, 0xc5, 0xbf, 0xc7, 0x01, 0x00, 0x00,
}
