const currencies = [
  { code: "AED", currency: "United Arab Emirates Dirham" },
  { code: "ARS", currency: "Argentine Peso" },
  { code: "AUD", currency: "Australian Dollar" },
  { code: "BDT", currency: "Bangladeshi Taka" },
  { code: "BHD", currency: "Bahraini Dinar" },
  { code: "BMD", currency: "Bermudian Dollar" },
  { code: "BRL", currency: "Brazilian Real" },
  { code: "CAD", currency: "Canadian Dollar" },
  { code: "CFH", currency: "Swiss Franc" },
  { code: "CLP", currency: "Chilean Peso" },
  { code: "CNY", currency: "Renminbi" },
  { code: "CZK", currency: "Czech Koruna" },
  { code: "DKK", currency: "Danish Krone" },
  { code: "EUR", currency: "Euro" },
  { code: "GBP", currency: "Pound Sterling" },
  { code: "HKD", currency: "Hong Kong Dollar" },
  { code: "HUF", currency: "Hungarian Forint" },
  { code: "IDR", currency: "Indonesian Rupiah" },
  { code: "ILS", currency: "Israeli New Shekel" },
  { code: "INR", currency: "Indian Rupee" },
  { code: "JPY", currency: "Japanese Yen" },
  { code: "KRW", currency: "South Korean Won" },
  { code: "KWD", currency: "Kuwaiti Dinar" },
  { code: "LKR", currency: "Sri Lankan Rupee" },
  { code: "MMK", currency: "Myanmar Kyat" },
  { code: "MXN", currency: "Mexican Peso" },
  { code: "MYR", currency: "Malaysian Ringgit" },
  { code: "NGN", currency: "Nigerian Naira" },
  { code: "NOK", currency: "Norwegian Krone" },
  { code: "NZD", currency: "New Zealand Dollar" },
  { code: "PHP", currency: "Philippine Peso" },
  { code: "PKR", currency: "Pakistani Rupee" },
  { code: "PLN", currency: "Polish Złoty" },
  { code: "RUB", currency: "Russian Ruble" },
  { code: "SAR", currency: "Saudi Riyal" },
  { code: "SEK", currency: "Swedish Krona" },
  { code: "SGD", currency: "Singapore Dollar" },
  { code: "THB", currency: "Thai Baht" },
  { code: "TRY", currency: "Turkish Lira" },
  { code: "TWD", currency: "New Taiwan Dollar" },
  { code: "UAH", currency: "Ukrainian Hryvnia" },
  { code: "USD", currency: "United States Dollar" },
  { code: "VEF", currency: "Venezuelan Bolívar Fuerte" },
  { code: "VND", currency: "Vietnamese Dồng" },
  { code: "ZAR", currency: "South African Rand" },
];

export default currencies;
