[package]
name = "bid-circuits"
version = "0.1.0"
authors = ["Jules de Smit <jules@dusk.network>"]
edition = "2018"


[dependencies]
anyhow = "1"
dusk-plonk = "0.5"
plonk_gadgets = "0.5"
dusk-blindbid = "0.6"
rand = "0.7"
