[package]
name = "host_fn"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-core = { workspace = true }
dusk-bytes = { workspace = true }
rusk-abi = { workspace = true, features = ["abi", "dlmalloc"]}
