[package]
name = "dusk-stake-contract-dd"
version = "0.1.1-alpha.1"
edition = "2021"

description = "Data driver for Dusk Stake Contract"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/rusk"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-core = { workspace = true, features = ["serde"] }

# data-driver dependency
dusk-data-driver = { workspace = true }

[features]
ffi = ["dusk-data-driver/wasm-export"]
js = ["ffi", "dusk-data-driver/alloc"]
