[package]
name = "dusk-stake-contract-dd"
version = "0.1.0"
edition = "2021"

description = "Data driver for Dusk Stake Contract"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/rusk"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-core = { workspace = true, features = ["serde"] }

# data-driver dependency
dusk-data-driver = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { workspace = true }
dlmalloc = { workspace = true, features = ["global"] }
