name: data-drivers CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  # Detect changes scoped to data-drivers
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      run-ci: ${{ steps.filter.outputs.run-ci }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            run-ci:
              - 'data-drivers/**'
              - '.github/workflows/data_drivers_ci.yml'

  npm-checks:
    needs: changes
    if: needs.changes.outputs.run-ci == 'true' && (github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Node 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setting up Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          scope: "@dusk-network"
          cache: npm
          cache-dependency-path: ./data-drivers/package-lock.json

      - name: Installing dependencies
        run: npm ci
        working-directory: ./data-drivers

      - name: Run checks
        run: npm run checks
        working-directory: ./data-drivers
